version: "3"
services:
  strapi:
    image: node:16
    container_name: major-cms
    command: ${COMMAND}
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
    volumes:
      - ./strapi-project:/data
    working_dir: /data
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: major-cms-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
